### ISSUE TITLE
Optional exit with 0 if build fail?

### ISSUE THREAD

**Issue by fanatid** [prebuild/node-gyp-build#28]
Right now, if `install` script is `node-gyp-build` and user do not have required tools / libraries on machine `npm install` will fail with exit code 1. But it's can be ok if we have pure js replacement of native bindings (for example [cryptocoinjs/secp256k1-node](https://github.com/cryptocoinjs/secp256k1-node), [cryptocoinjs/keccak](https://github.com/cryptocoinjs/keccak)).

What if we add flag `--ignore-build-fail` with `node-gyp-build` will exit with 0 for any result of `node-gyp rebuild`?

**Comment by vweevers** [comment]
Would this work?

```
"scripts": {
    "install": "node-gyp-build || exit 0"
  }
```

**Comment by fanatid** [comment]
Yeah, I use `||` in secp256k1/keccak, but devs still create issues about building. Not sure why, error message or npm fail actually.
Does `||` works on all platforms? (win32)

**Comment by vweevers** [comment]
Yes, also works on Windows.
