### ISSUE TITLE
require in node-gyp-build-test causes prebuild detection to fail

### ISSUE THREAD

**Issue by SnosMe** [prebuild/node-gyp-build#29]
Hi, I have an issue with this line

https://github.com/prebuild/node-gyp-build/blob/f5f31028918bffb872908d066209bf3ef0fcc7b3/build-test.js#L19

I wrapped [libuiohook](https://github.com/kwhat/libuiohook) using N-API in [uiohook-napi](https://github.com/SnosMe/uiohook-napi). 
libuiohook uses some [compiler specific code](https://www.tutorialspoint.com/attribute-constructor-and-attribute-destructor-syntaxes-in-c-in-tutorials-point), we can speak about it as side effects on `require()`.

So basically when I try to install my package on linux without desktop environment (CI builds), I got this
```bash
npm info lifecycle uiohook-napi@1.0.4~install: uiohook-napi@1.0.4

> uiohook-napi@1.0.4 install /home/runner/work/test-ci-bug/test-ci-bug/node_modules/uiohook-napi
> node-gyp-build

on_library_load [441]: XOpenDisplay failure!
settings_thread_proc [121]: XOpenDisplay failure!
load_input_helper [1797]: XkbGetKeyboard failed to locate a valid keyboard!
Segmentation fault (core dumped)
```

Because obviously there is no [X11](https://en.wikipedia.org/wiki/X_Window_System), `node-gyp-build-test` process crashes and `node-gyp rebuild` is triggered.

My proposal is to add some flag like `--naive`, that will just check `*.node` file existence, not actually `require`-ing it.

**Comment by SnosMe** [comment]
As a workaround, I use

```json
  "prebuild": {
    "test": "dist/prebuild-test-noop.js"
  }
```

**Comment by vweevers** [comment]
The `require` check has an important purpose: check if a prebuild is compatible and fallback to compiling if not.

Which CI provider are you using? On Travis for example, you could use xvfb.

**Comment by mafintosh** [comment]
You can also use node-gyp-build-optional to not run the check and trigger compilation
