### ISSUE TITLE
getting error node-gyp-build 

### ISSUE THREAD

**Issue by samgegr8** [prebuild/node-gyp-build#34]
Hi Team,

Docker build is failing with node build error as below

> bufferutil@4.0.1 install /opt/atlassian/pipelines/agent/build/node_modules/bufferutil
> node-gyp-build
make: Entering directory `/opt/atlassian/pipelines/agent/build/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
../src/bufferutil.c:3:22: fatal error: node_api.h: No such file or directory
 #include <node_api.h>

Attached is the compile error file . I am using Bitbucket pipeline.[
[pipelineLog-264.txt](https://github.com/prebuild/node-gyp-build/files/5073578/pipelineLog-264.txt)
](url)

**Comment by vweevers** [comment]
```
gyp ERR! node -v v4.2.1
```

You need a newer version of node, likely at least node 8, check [bufferutil](https://github.com/websockets/bufferutil) to be sure.

**Comment by samgegr8** [comment]
My package.json has higher version 

' "dependencies": {
        "async": "^3.2.0",
        "bufferutil": "^4.0.1",
        "csvtojson": "^2.0.0",
        "json2csv": "^5.0.0",
        "moment-timezone": "^0.5.28",
        "utf-8-validate": "^5.0.2"
    },
    "devDependencies": {
        "@types/async": "^3.2.1",
        "@types/aws-lambda": "^8.10.36",
        "@types/dotenv": "^8.2.0",
        "@types/jest": "^24.0.11",
        "@types/json2csv": "^5.0.0",
        "@types/moment-timezone": "^0.5.4",
        "@types/node": "^12.0.0",
        "@typescript-eslint/eslint-plugin": "^2.6.0",
        "@typescript-eslint/parser": "^2.6.0",
        "aws-sdk": "^2.0.0",
        "aws-sdk-mock": "^5.1.0",
        "aws-xray-sdk": "^2.5.0",
        "dotenv": "^8.2.0",
        "eslint": "^6.0.1",
        "eslint-config-prettier": "^6.0.0",
        "eslint-plugin-prettier": "^3.1.3",
        "fork-ts-checker-webpack-plugin": "^3.0.1",
        "jest": "^25.5.0",
        "prettier": "^2.0.5",
        "serverless": "^1.71.1",
        "serverless-dotenv-plugin": "^2.1.1",
        "serverless-iam-roles-per-function": "^2.0.1",
        "serverless-offline": "^5.12.0",
        "serverless-plugin-existing-s3": "^2.4.0",
        "serverless-pseudo-parameters": "^2.4.0",
        "serverless-s3-remover": "^0.6.0",
        "serverless-webpack": "^5.2.0",
        "source-map-support": "^0.5.19",
        "ts-jest": "^24.3.0",
        "ts-loader": "^6.2.1",
        "ts-node": "^8.8.0",
        "typescript": "^3.6.2",
        "uuid": "^3.3.3",
        "webpack": "^4.29.0",
        "webpack-node-externals": "^1.7.2"
    }
}'

**Comment by samgegr8** [comment]
issue solved so closing it

**Comment by payalpamnani** [comment]
Please share how was this issue resolved.. am still getting this error on my Angular web app thats on Node 6.9.1 and bufferutil available version is 4.0.1

**Comment by vweevers** [comment]
You need a newer version of node.

**Comment by payalpamnani** [comment]
whats minimum that works with this bufferutil version?

**Comment by vweevers** [comment]
Likely 8 or 10, check or ask in https://github.com/websockets/bufferutil.
