### ISSUE TITLE
Understanding if prebuilds are being used or not

### ISSUE THREAD

**Issue by alcuadrado** [prebuild/node-gyp-build#36]
Hi,

I'm using a few packages that use `node-gyp-build`, and I'm having a hard time figuring out if I'm using native versions of those or their js fallback. Is there a way I can distinguish between them?

**Comment by alcuadrado** [comment]
An alternative would be a way to make the package or its installation fail if it can't use the prebuilt version.

**Comment by vweevers** [comment]
Is the question about distinguishing prebuilt binaries from binaries compiled from source? In which case, you can set `PREBUILDS_ONLY=1` in the env which tells `node-gyp-build` to only load a prebuilt binary (i.e. skipping `build/Release/`).

Or is the question about distinguishing native addons from JS fallbacks? Which is not something that `node-gyp-build` handles, packages need their own logic for that.

**Comment by alcuadrado** [comment]
Thanks for the quick reply, I was looking for the second option. I'd try to come up with a way of doing this at the package level.
