### ISSUE TITLE
question: is node-gyp required as a dependency?

### ISSUE THREAD

**Issue by DavidVujic** [prebuild/node-gyp-build#41]
When using `node-gyp-build` to build a Node.js native addon:
is the `node-gyp` package required in the project too, or does `node-gyp-build` have the same capabilities?

In my Node.js project, I have a `binding.gyp` file, C and C++ code. I use `node-gyp-build` and also `prebuildify` to create prebuilds to speed up local development.

**Comment by vweevers** [comment]
The `node-gyp` package comes bundled with npm (meaning all users have it) and that's what `node-gyp-build` uses by default. In order to use a newer (or older, or just consistent) version of `node-gyp`, you can add it to your dependencies, and then `node-gyp-build` will prefer that over the npm-bundled one.

**Comment by vweevers** [comment]
Actually let me double-check that - I might be confusing `prebuildify` behavior with `node-gyp-build`.

**Comment by vweevers** [comment]
OK I checked, `prebuildify` has a [workaround](https://github.com/prebuild/prebuildify/blob/3508f26448f609c0334894d5deff17b52f2c39d8/index.js#L66-L68) to override the npm-bundled `node-gyp` but `node-gyp-build` does not. In other words, for `node-gyp-build` you do not need to add `node-gyp` to your dependencies and even if you did it would not make a difference (for end users). You can choose to add `node-gyp` to your devDependencies though, if you need that for `prebuildify`.

**Comment by DavidVujic** [comment]
Thank you for clarifying!

That makes total sense, because I had by accident put `node-gyp` in the `devDepencencies` section of my project (but all things still working fine). 😄
