### ISSUE TITLE
Next.js does not bring over prebuilds folder into .next/server: "No native build was found for ..."

### ISSUE THREAD

**Issue by eulersson** [prebuild/node-gyp-build#65]
When using a dependency that uses `node-gyp-build` prebuilt binaries, next does not seem to pick up those binaries.

The directory it searches for binaries is `./.next/server` instead of `./node_modules/zeromq` in my case. If I change this and hardcode it to `/absolute/path/to/node_modules/zeromq` it works because it sees that `prebuilds`.

https://github.com/prebuild/node-gyp-build/blob/0078d7884dfeb0e708477b3e20bfc4f520c1e2f8/index.js#L26 

As you might have noticed I am using a fork that was made on `4.5.0`, because that's what was done for https://github.com/zeromq/zeromq.js

> [!NOTE]
> Reproduce by cloning https://github.com/eulersson/zeromq.js-next.js-errors, `npm install`, `npm run dev`. Or by running the Docker container in there.

**Comment by mafintosh** [comment]
are you passing the __dirname to the exported func? sounds like you are passing the wrong dir

**Comment by eulersson** [comment]
> are you passing the __dirname to the exported func? sounds like you are passing the wrong dir

Many thanks for your response.

Can I set up the `__dirname` to be different just for one dependency? I guess the `__dirname` is fine to be at `.next/server`? I guess the the desired outcome would be to have the `prebuilds` folder in the `.next/server` somehow.

Do you know any other project that uses node-gyp-built deps with prebuilds in the context of a Next.js? Maybe it would help to see how people resolve this issue...

**Comment by mafintosh** [comment]
You can just “hoist” all the prebuilds from node_modules into that folder if the deps are on latest node-gyp-build. Ie mb move node_modules/sodium-native/prebuilds into .next/server/prebuilds 

in a later version all the prebuilds are named so you can have them all in the same folder

**Comment by eulersson** [comment]
If I move them manually and run `npm run dev` it cleans the entire `.next/server` and repopulates it missing the files I just copied. It does not seem to persist. I guess somewhere Next.js needs to be informed about those. I don't know what building infrastructure Next.js uses, maybe there's webpack involved underneath but I am not sure.

**Comment by eulersson** [comment]
The problem has been identified, it's with vercel's file tracing tool "nft". I will provide a PR tomorrow. If someone is having this problem go to the issue on vercel's side https://github.com/vercel/nft/issues/391, I will therefore close his one. Thanks @mafintosh for the response :)

**Comment by eulersson** [comment]
Actually I want to say I will fix it not in the elegant way of making the tool be able to dynamically resolve the path but to add a special case. In the future more users using node-gyp-build might run into similar problems but for now I will do it like @styfle suggested in this comment https://github.com/vercel/nft/issues/391#issuecomment-1938785569

**Comment by eulersson** [comment]
Will be fixed if all goes will with this issue resolution https://github.com/vercel/nft/issues/391 with PR https://github.com/vercel/nft/pull/392.

**Comment by eulersson** [comment]
`@vercel/nft` version `0.26.4` fixes it.
